apiVersion: v1
kind: Service
metadata:
  name: mysvc
  labels:
    app: mysvc
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  - port: 8088
    targetPort: 8088
    name: prom
  selector:
    app: myapp
  type: NodePort