apiVersion: apps/v1
kind: Deployment
metadata:
  name: two-containers
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: tomact
        image: tomcat:9.0.34
        ports:
        - containerPort: 8080
      - name: exporter
        image: chakilams3/latesttomcat:latest
        ports:
        - containerPort: 8080



