apiVersion: apps/v1
kind: Deployment
metadata :
  name: webv1
spec:
  replicas: 4
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: chakilams3/k8sdemo:webv1
        readinessProbe:
          httpGet:
          path: /
          port: 80
          httpHeaders:
          - name: Host
            value: K8sProbe


chakilams3/jmxtomcat:v1
