FROM tomcat:9.0.34

ADD simpleclient-0.8.1.jar /usr/local/tomcat/lib/simpleclient-0.8.1.jar
ADD simpleclient_common-0.8.1.jar /usr/local/tomcat/lib/simpleclient_common-0.8.1.jar
ADD simpleclient_hotspot-0.8.1.jar /usr/local/tomcat/lib/simpleclient_hotspot-0.8.1.jar
ADD simpleclient_servlet-0.8.1.jar /usr/local/tomcat/lib/simpleclient_servlet-0.8.1.jar
ADD tomcat_exporter_client-0.0.13.jar /usr/local/tomcat/lib/tomcat_exporter_client-0.0.13.jar
ADD sample.war /usr/local/tomcat/webapps/sample.war
ADD metrics.war /usr/local/tomcat/webapps/metrics.war