apiVersion: v1
kind: Service
metadata:
  name: exporter-service
  labels:
    app: exporter
spec:
  selector:
    app: exporter
  type: NodePort
  ports:
  - nodePort: 31000
    port: 8080
    targetPort: 8080