apiVersion: v1
kind: ReplicaSet
metdata:
  name: myapp-replicaset
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx-container
          image: nginx: latest
  replicas: 3
  selector:
    matchLabels:
      app: myapp



